[build]
  publish = "dist"  # Folder containing index.html, CSS, JS
  functions = "functions"  # Folder containing your serverless functions

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/api"
  status = 200
